name: Ajouter une relation au CSV
on:
  issues:
    types: [opened,labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  add-relation:
    if: |
      contains(github.event.issue.labels.*.name, 'ajout') &&
      contains(github.event.issue.labels.*.name, 'relation')
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Ajouter relation au CSV
        run: python add_relation.py
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}

      - name: Cr√©er PR
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Ajout relation #${{ github.event.issue.number }}"
          branch: ajout-relation-${{ github.event.issue.number }}
